import Head from "next/head"
export default function Buy() {
    return (
        
        <div>
            Buy Page 
            <Head>
                <title>KH Real Eatate - Buy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon-re.png" />
                <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
            </Head>
        </div>
    )
}