import Head from 'next/head'
import { HeaderTop } from '../components/HeaderTop'
import { HomeBanner } from '../components/HomeBanner'
import { Nav } from '../components/Nav'
import styles from '../styles/HeaderTop.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KH Real Eatate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-re.png" />
        <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
      </Head>
      <HeaderTop />
      <Nav />
      <HomeBanner />
    </div>
  )
}
