import Head from 'next/head'
import { HomeBanner } from '../components/HomeBanner'
import { HomeBuy } from '../components/HomeBuy'
import { HomeRent } from '../components/HomeRent'
import { NewDev } from '../components/NewDev'
import { PopularLocation } from '../components/PopularLocation'
import style from '../styles/Hody.module.css'
export default function Home() {
  return (
    <div className={style.container}>
        <Head>
          <title>KH Real Eatate</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-re.png" />
          <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
        </Head>
        <HomeBanner />
        <NewDev />
        <HomeBuy />
        <HomeRent /> 
        <PopularLocation />
    </div>
  )
}
