import React from 'react';
import Head from "next/head"
import { HomeBuy } from '../components/HomeBuy'
import { Footer } from '../components/Footer'
export default function Rent () {
    return (
        <div>
            <Head>
                <title>KH Real Eatate - Buy</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon-re.png" />
                <script src="https://unpkg.com/boxicons@2.1.1/dist/boxicons.js"></script>
            </Head>
            <HomeBuy title='Residentails'/>
            <HomeBuy title='Commercial'/>
            <HomeBuy title='Land' />
            <Footer/>
        </div>
    )
};
